### ISSUE TITLE
댓글 좋아요가 눌러지지 않음

### ISSUE THREAD

**Issue by ONSISU** [Zelkova-Project/FE#63]

**Comment by TomHoon** [comment]
회원정보 체크를 현재는 localStorage로 체크하고 있습니다.
이전 로직인 쿠키로 체크하는 소스가 남아있어서 제거하고 반영되었습니다. 

axios interceptor에서 토큰을 날려주고 있어
쿠키로 사용할 필요가 없어서 localStorage로 저장하여 처리하고 있습니다. 

확인 후 재현이 안되면 이슈 종료 부탁드립니다~
